[git_branch]
style = "purple"

[gcloud]
disabled = true

[kubernetes]
disabled = false
style = "bold fg:18 bg:117"
[kubernetes.context_aliases]
"dev-orscale-01-dm-dc3" = "dev-01"
"dev-orscale-02-dm-dc3" = "dev-02"
"staging-orscale-01-dm-ix7" = "staging"
"prod-orscale-01-dm-ix7" = "prod-ix7"
"prod-orscale-01-dm-sv4" = "prod-sv4"
"prod-orscale-01-dm-sg1" = "prod-sg1"
"prod-orscale-01-dm-dc3" = "prod-dc3"

[cmd_duration]
min_time = 500
